apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::050752612257:role/eksctl-expense-nodegroup-expense-n-NodeInstanceRole-VJT4n0777obq
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::050752612257:user/harish
      username: harish
kind: ConfigMap
metadata:
  creationTimestamp: "2025-06-01T09:17:48Z"
  name: aws-auth
  namespace: kube-system
  uid: b53841bf-2875-4b0e-b298-d95ba47287d9
